pipeline {
    agent any

    tools {
        // Make sure you have configured Maven in Jenkins Global Tool Configuration with this exact name
        maven 'Maven'
        jdk 'JDK-21'
    }

    stages {
        stage('Clone Repository') {
            steps {
                // Checkout your repo's main branch
                git branch: 'main', url: 'https://github.com/Sabeshragav/jenkins-java-2'
            }
        }

        stage('Build with Maven') {
            steps {
                // Clean and build the Maven project, fail build on error
                bat 'mvn clean package' 
            }
        }

        // stage('Archive Artifact') {
        //     steps {
        //         // Archive any jar file(s) generated inside the target directory
        //         archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
        //     }
        // }

        stage('Executing jar file') {
            steps {
                // Execute the jar file generated by Maven
                bat 'java -cp target/myfirstapp-1.jar com.devops.example.App' 
            }
        }
    }

    post {
        success {
            echo 'Build and archive completed successfully!'
        }
        failure {
            echo 'Build failed! Check console output for errors.'
        }
    }
}